import { ColorPalette } from '../../types/design.js';

export const neutralDarkPalettes: ColorPalette[] = [
  {
    id: 'neutral-dark-1',
    name: 'Midnight Gold',
    primary: '#D4AF37',
    accent: '#F4E5C2',
    background: '#0A0A0A',
    surface: '#1A1A1A',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0A0',
    success: '#4ADE80',
    warning: '#FBBF24',
    error: '#F87171',
  },
  {
    id: 'neutral-dark-2',
    name: 'Deep Ocean',
    primary: '#60A5FA',
    accent: '#93C5FD',
    background: '#0F172A',
    surface: '#1E293B',
    textPrimary: '#F1F5F9',
    textSecondary: '#94A3B8',
    success: '#34D399',
    warning: '#FBBF24',
    error: '#F87171',
  },
  {
    id: 'neutral-dark-3',
    name: 'Charcoal',
    primary: '#A78BFA',
    accent: '#C4B5FD',
    background: '#18181B',
    surface: '#27272A',
    textPrimary: '#FAFAFA',
    textSecondary: '#A1A1AA',
    success: '#4ADE80',
    warning: '#FBBF24',
    error: '#F87171',
  },
  {
    id: 'neutral-dark-4',
    name: 'Forest Night',
    primary: '#6EE7B7',
    accent: '#A7F3D0',
    background: '#0F1419',
    surface: '#1A2332',
    textPrimary: '#F0F9FF',
    textSecondary: '#94A3B8',
    success: '#34D399',
    warning: '#FCD34D',
    error: '#FCA5A5',
  },
  {
    id: 'neutral-dark-5',
    name: 'Obsidian',
    primary: '#F472B6',
    accent: '#F9A8D4',
    background: '#0C0A09',
    surface: '#1C1917',
    textPrimary: '#FAFAF9',
    textSecondary: '#A8A29E',
    success: '#86EFAC',
    warning: '#FCD34D',
    error: '#FCA5A5',
  },
];
