import { ColorPalette } from '../../types/design.js';

export const vibrantPalettes: ColorPalette[] = [
  {
    id: 'vibrant-1',
    name: 'Candy Pop',
    primary: '#FF6B9D',
    accent: '#FFD93D',
    background: '#FFF5F7',
    surface: '#FFFFFF',
    textPrimary: '#2D1B3D',
    textSecondary: '#6B5B7B',
    success: '#4ECDC4',
    warning: '#FFA07A',
    error: '#FF6B6B',
  },
  {
    id: 'vibrant-2',
    name: 'Aurora',
    primary: '#6366F1',
    accent: '#8B5CF6',
    background: '#F5F3FF',
    surface: '#FFFFFF',
    textPrimary: '#1E1B4B',
    textSecondary: '#6B7280',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
  },
  {
    id: 'vibrant-3',
    name: 'Sunset Retro',
    primary: '#FF6B6B',
    accent: '#FFE66D',
    background: '#FFF9E6',
    surface: '#FFFFFF',
    textPrimary: '#2D3436',
    textSecondary: '#636E72',
    success: '#55E6C1',
    warning: '#FFA502',
    error: '#FF4757',
  },
  {
    id: 'vibrant-4',
    name: 'Electric',
    primary: '#00D9FF',
    accent: '#FF00E5',
    background: '#0A0E27',
    surface: '#1A1F3A',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0AEC0',
    success: '#00F5A0',
    warning: '#FFD700',
    error: '#FF4757',
  },
  {
    id: 'vibrant-5',
    name: 'Tropical',
    primary: '#00B894',
    accent: '#FDCB6E',
    background: '#F0FFF4',
    surface: '#FFFFFF',
    textPrimary: '#2D3436',
    textSecondary: '#636E72',
    success: '#00CEC9',
    warning: '#F39C12',
    error: '#E17055',
  },
];
